# @Author: Wendy Guadalupe Magaña Argente <wendylu>
# @Date:   2017-09-05T05:17:09-05:00
# @Email:  wendyargente@nube.unadmexico.mx
# @Project: Turing
# @Filename: _config.yml
# @Last modified by:   wendylu
# @Last modified time: 2017-09-05T19:36:18-05:00
# @License: MIT



# Welcome to Jekyll!
#
# Archivo para producción
#
title: Biblioteca Virtual Turing
email: wendyargente@nube.unadmexico.mx
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/turing/" # the subpath of your site, e.g. /blog
url: "https://wendyar.github.io" # the base hostname & protocol for your site, e.g. http://example.com


# Build settings
markdown: kramdown

sass:
    sass_dir: _sass

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude: [documentacion, Gemfile, Gemfile.lock]
